services:
  postgres:
    image: postgres:16-alpine
    container_name: budgety-postgres
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: budgety
      POSTGRES_PASSWORD: budgety
      POSTGRES_DB: budgety
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
